/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

import Modelo.Academia;
import Modelo.Categoria;
import Modelo.Curso;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author 203pc19
 */
public class MiVentana extends javax.swing.JFrame {

    DefaultComboBoxModel modelo;//objeto de tipo comboBox del cmbPago
    DefaultComboBoxModel modelo2;//pertenece al cmbCategorias
    //CursosOfertados, PreciosOfertados, CursosElegidos, PreciosElegidos
    DefaultListModel modelo3, modelo4, modelo5, modelo6;
    Academia miAcademia;
    Categoria miCategoria;

    public MiVentana() {
        initComponents();
        modelo = new DefaultComboBoxModel();
        cmbPago.setModel(modelo);
        modelo2 = new DefaultComboBoxModel();
        cmbCategorias.setModel(modelo2);
        cargarComboPago();
        Categoria[] c = crearAcademia();
        miAcademia = new Academia(c);

        modelo3 = new DefaultListModel();
        modelo4 = new DefaultListModel();
        modelo5 = new DefaultListModel();
        modelo6 = new DefaultListModel();

        lstCursosOfertados.setModel(modelo3);
        lstPreciosOfertados.setModel(modelo4);
        lstCursosElegidos.setModel(modelo5);
        lstPreciosElegidos.setModel(modelo6);
        cargarComboCateg();

    }

    private Categoria[] crearAcademia() {
        Categoria[] c = new Categoria[3];
        Curso[] curso1 = {new Curso("Java", 23), new Curso("Visual", 15)};
        c[0] = new Categoria("Programación", curso1);
        Curso[] curso2 = {new Curso("Photoshop", 53), new Curso("Corel Draw", 22)};
        c[1] = new Categoria("Diseño Gráfico", curso2);
        Curso[] curso3 = {new Curso("Francés", 25), new Curso("Ingles", 30)};
        c[2] = new Categoria("Idiomas", curso3);
        return c;
    }

    private void cargarComboPago() {
        //Ponemos un array con las diferentes formas de pago
        //Es lo que se mostrará en el comboBox que a su objeto le hemos llamado modelo
        String[] datos = {"Contado", "Tarjeta debito", "Tarjeta crédito"};
        for (int i = 0; i < datos.length; i++) {
            modelo.addElement(datos[i]);
        }
    }

    private void cargarComboCateg() {
        Categoria[] c = miAcademia.getCategorias();//GUARDAMOS TODAS LAS CATEGORIAS DE LA ACADEMIA
        int i = 0;
        for (i = 0; i < c.length; i++) {
            modelo2.addElement(miAcademia.getUnaCategoria(i).getDenominacion());
        }
    }

    private void cargarCursos2(int pos) {
        Curso[] c = miAcademia.getUnaCategoria(pos).getCursos();//GUARDAMOS LOS CURSOS DE CADA CATEGORIA
        for (int i = 0; i < c.length; i++) {
            modelo3.addElement(c[i].getNombre());
            modelo4.addElement(c[i].getImporte());
            int a = i;
            /* String nombre = (String) cmbCategorias.getSelectedItem();
            if (miAcademia.getUnaCategoria(pos).getDenominacion().compareToIgnoreCase(nombre) == 0) {
                if(pos<miAcademia.getCategorias().length && a==c.length){
                modelo3.clear();
                modelo4.clear();
                }
            }*/
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbPago = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txtAlumno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbCategorias = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCursosOfertados = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPreciosOfertados = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstCursosElegidos = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstPreciosElegidos = new javax.swing.JList();
        btnQuitar = new javax.swing.JButton();
        btnAgregar1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtTotalCursos = new javax.swing.JTextField();
        etIncremento = new javax.swing.JLabel();
        txtIncremento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setFont(new java.awt.Font("Century", 0, 10)); // NOI18N

        cmbPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPagoActionPerformed(evt);
            }
        });

        jLabel1.setText("ALUMNO");

        jLabel2.setText("Categoría de Cursos");

        cmbCategorias.setToolTipText("");
        cmbCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriasActionPerformed(evt);
            }
        });

        jLabel3.setText("Cursos Ofertados");

        jLabel4.setText("Coste");

        lstCursosOfertados.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCursosOfertadosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstCursosOfertados);

        lstPreciosOfertados.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPreciosOfertadosValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstPreciosOfertados);

        jLabel5.setText("Cursos Escogidos");

        jLabel6.setText("Coste");

        lstCursosElegidos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCursosElegidosValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstCursosElegidos);

        lstPreciosElegidos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPreciosElegidosValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(lstPreciosElegidos);

        btnQuitar.setText("<<");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        btnAgregar1.setText(">>");
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Forma de Pago");

        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnCerrar.setText("CERRAR");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jLabel8.setText("TOTAL");

        txtTotalCursos.setEditable(false);

        etIncremento.setText("Incremento");

        txtIncremento.setEditable(false);

        jLabel9.setText("Descuento");

        txtDescuento.setEditable(false);

        jLabel10.setText("Total");

        txtTotal.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etIncremento)
                        .addGap(18, 18, 18)
                        .addComponent(txtIncremento, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cmbPago, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(btnCalcular)
                                    .addGap(42, 42, 42)
                                    .addComponent(btnLimpiar))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCerrar)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTotalCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(cmbCategorias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(btnAgregar1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnQuitar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtTotalCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(btnLimpiar)
                    .addComponent(btnCerrar))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etIncremento)
                    .addComponent(txtIncremento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPagoActionPerformed
        /*Le decimos que muestre un objeto de tipo String. De esa forma nos aseguramos de que
         no falle si le metemos otro tipo de dato.
         Si no le ponemos String, el dato te lo va mostrar igual pero
         puede fallar si le ponemos otro tipo de dato*/
        //JOptionPane.showMessageDialog(this, (String) cmbPago.getSelectedItem());
    }//GEN-LAST:event_cmbPagoActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
               Curso c;                                                            
        float importe;                                                      
        int indice = lstCursosElegidos.getSelectedIndex();            
        if (indice == -1) {                                                 
            JOptionPane.showMessageDialog(this, "SELECCIONA UN CURSO");     
        } else {                                                            
            String nombre = (String) lstCursosElegidos.getSelectedValue();          
            importe = (Float) lstPreciosElegidos.getSelectedValue();   
            modelo3.addElement(nombre);                                         
            modelo4.addElement(importe);                                    
            modelo5.remove(indice);                                         
            modelo6.remove(indice);                                         
            calculoImporte();                                              
            //calculo();
        }
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void lstCursosOfertadosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCursosOfertadosValueChanged
        int indice;
        indice = lstCursosOfertados.getSelectedIndex();
        lstPreciosOfertados.setSelectedIndex(indice);
    }//GEN-LAST:event_lstCursosOfertadosValueChanged

    private void lstPreciosOfertadosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPreciosOfertadosValueChanged
        /*Con este método hacemos que cuando damos en un precio me coga el curso tambien*/
        int indice;
        indice = lstPreciosOfertados.getSelectedIndex();//Con estas dos lineas hacemos la seleccion a la vez
        lstCursosOfertados.setSelectedIndex(indice);
    }//GEN-LAST:event_lstPreciosOfertadosValueChanged

    private void lstCursosElegidosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCursosElegidosValueChanged
        int indice;
        indice = lstCursosElegidos.getSelectedIndex();
        lstPreciosElegidos.setSelectedIndex(indice);
    }//GEN-LAST:event_lstCursosElegidosValueChanged

    private void lstPreciosElegidosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPreciosElegidosValueChanged
        int indice;
        indice = lstPreciosElegidos.getSelectedIndex();
        lstCursosElegidos.setSelectedIndex(indice);
    }//GEN-LAST:event_lstPreciosElegidosValueChanged

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void cmbCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriasActionPerformed
        String nombre = (String) cmbCategorias.getSelectedItem();//le decimos que el nombre será a lo que selecionemos en categorias
        int pos = miAcademia.buscarCategoria(nombre);
        modelo3.clear();
        modelo4.clear();
        cargarCursos2(pos);
    }//GEN-LAST:event_cmbCategoriasActionPerformed

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
        //Curso c;//con el objeto "c" llamamos a la denomincacion de la clase Curso
        float importe;
        int indice = lstCursosOfertados.getSelectedIndex();
        if (indice == -1) {
            JOptionPane.showMessageDialog(this, "Primero selecciona el curso");
        } else {
            String nombre = (String) lstCursosOfertados.getSelectedValue();
            importe = (Float) lstPreciosOfertados.getSelectedValue();
            modelo3.remove(indice);
            modelo4.remove(indice);
            modelo5.addElement(nombre);//el "addElement" te lo agrega al final del siguiente elmento
            modelo6.addElement(importe);
 
            calculoImporte();
    }//GEN-LAST:event_btnAgregar1ActionPerformed
    }
    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        float descuento = 0, incremento = 0, totalCursos, totalPagar;
        try {

            totalCursos = Float.parseFloat(txtTotalCursos.getText());
            if (cmbPago.getSelectedItem().toString().compareToIgnoreCase("Contado") == 0) {
                incremento = 0;
                descuento = 0.5f * totalCursos;
            } else if (cmbPago.getSelectedItem().toString().compareToIgnoreCase("Tarjeta debito") == 0) {
                incremento = 0.25f * totalCursos;
                descuento = 0;
            } else if (cmbPago.getSelectedItem().toString().compareToIgnoreCase("Tarjeta crédito") == 0) {
                incremento = 0.1f * totalCursos;
                descuento = 0;
            }
            totalPagar = totalCursos + incremento - descuento;
            //ESTAS TRES SIGUIENTES LÍNEAS SIRVEN PARA CONVERTIR LOS VALORES A STRING
            //para que no de error y lo pueda mostrar
            txtTotal.setText(String.valueOf(totalPagar));
            txtDescuento.setText(String.valueOf(descuento));
            txtIncremento.setText(String.valueOf(incremento));

            File archivo = new File("texto.txt");//Crear un objeto File se encarga de crear o abrir acceso a un archivo que se especifica en su constructor
            FileWriter escribir = new FileWriter(archivo, true);//Crear objeto FileWriter que sera el que nos ayude a escribir sobre archivo

            escribir.write(Float.toString(descuento));//Escribimos en el archivo con el metodo write 
            escribir.write(Float.toString(incremento));
            escribir.write(Float.toString(totalPagar));
            escribir.close();
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "HAY QUE SELECCIONAR UN CURSO");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "ERROR AL ESSCRIBIR");
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        int pos = 0;
        txtAlumno.setText("");

//crearAcademia();
//modelo2.getListeners(categoria);
//cargarComboCateg();
        modelo3.clear();
        modelo4.clear();
        cargarCursos2(pos);

        modelo5.clear();
        modelo6.clear();

        txtTotalCursos.setText("");
        txtIncremento.setText("");
        txtDescuento.setText("");
        txtTotal.setText("");
        //btnCalcular.setEnabled(false);
        //btnLimpiar.setEnabled(false);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void calculoImporte() {
        float total = 0;
        for (int i = 0; i < modelo6.size(); i++) {//EL "SIZE" ES IGUAL QUE EL "LENGTH"
            /*Poniendo el float entre parentesis delanta, convertimos el valor del modelo4
             a tipo float. Se llama castear*/
            total = total + (float) modelo6.get(i);
        }
        txtTotalCursos.setText(String.valueOf(total));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JComboBox cmbCategorias;
    private javax.swing.JComboBox cmbPago;
    private javax.swing.JLabel etIncremento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList lstCursosElegidos;
    private javax.swing.JList lstCursosOfertados;
    private javax.swing.JList lstPreciosElegidos;
    private javax.swing.JList lstPreciosOfertados;
    private javax.swing.JTextField txtAlumno;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtIncremento;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalCursos;
    // End of variables declaration//GEN-END:variables
}
