/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import javax.swing.JOptionPane;

/**
 *
 * @author 203pc19
 */
public class Producto extends javax.swing.JFrame {

    /**
     * Creates new form Producto
     */
    public Producto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtCoste = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rbAudio = new javax.swing.JRadioButton();
        rbVideo = new javax.swing.JRadioButton();
        rbLinea = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        chkContado = new javax.swing.JCheckBox();
        btnCalcular = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnDescuento = new javax.swing.JLabel();
        btnIncremento = new javax.swing.JLabel();
        btnTotal = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JTextField();
        txtIncremento = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setText("COSTE DEL PRODUCTO");

        txtCoste.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCoste.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCosteFocusLost(evt);
            }
        });
        txtCoste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCosteActionPerformed(evt);
            }
        });
        txtCoste.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCosteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCosteKeyReleased(evt);
            }
        });

        jLabel2.setText("jLabel2");

        btnGrupo.add(rbAudio);
        rbAudio.setSelected(true);
        rbAudio.setText("Audio");
        rbAudio.setFocusable(false);
        rbAudio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbAudioStateChanged(evt);
            }
        });

        btnGrupo.add(rbVideo);
        rbVideo.setText("Vídeo");
        rbVideo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbVideoStateChanged(evt);
            }
        });

        btnGrupo.add(rbLinea);
        rbLinea.setText("Línea Blanca");
        rbLinea.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbLineaStateChanged(evt);
            }
        });

        jLabel3.setText("FORMA DE PAGO");

        chkContado.setText("Contado");

        btnCalcular.setText("CALCULAR");
        btnCalcular.setEnabled(false);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setEnabled(false);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnDescuento.setText("DESCUENTO");

        btnIncremento.setText("INCREMENTO");

        btnTotal.setText("TOTAL A PAGAR");

        txtDescuento.setEditable(false);

        txtIncremento.setEditable(false);

        txtTotal.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(80, 80, 80)
                        .addComponent(txtCoste, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbAudio)
                                .addGap(18, 18, 18)
                                .addComponent(rbVideo)
                                .addGap(18, 18, 18)
                                .addComponent(rbLinea))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(37, 37, 37)
                                    .addComponent(chkContado))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnTotal)
                                        .addComponent(btnIncremento)
                                        .addComponent(btnDescuento))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtDescuento, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                        .addComponent(txtIncremento)
                                        .addComponent(txtTotal)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir)
                    .addComponent(btnLimpiar)
                    .addComponent(btnCalcular))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCoste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnCalcular))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbAudio)
                            .addComponent(rbVideo)
                            .addComponent(rbLinea)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnLimpiar)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(chkContado)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnSalir)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDescuento)
                    .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncremento)
                    .addComponent(txtIncremento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCosteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCosteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCosteActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();//cierra la ventana y libera todos los recursos que este utlizando
        System.exit(0);//para cerrar la ventana
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtCoste.setText("");
        txtIncremento.setText("");
        txtDescuento.setText("");
        txtTotal.setText("");

        rbAudio.setSelected(true);
        rbVideo.setSelected(false);
        rbLinea.setSelected(false);
        rbAudio.setEnabled(true);
        rbVideo.setEnabled(true);
        rbLinea.setEnabled(true);

        chkContado.setSelected(false);
        btnCalcular.setEnabled(false);//le decimos que este o no este disponible
        btnLimpiar.setEnabled(false);

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        /*float coste;
        float descuento;
        float total;
        float incremento=0;
        try {
            coste = Float.parseFloat(txtCoste.getText());//PARA RECOGER LO QUE TIENES EN ESTA PROPIEDAD
            if (rbAudio.isSelected()) {
                descuento = coste * 0.1f;
            } else {
                if (rbVideo.isSelected()) {//si rbVideo está seleccionado, es decir, si es true
                    descuento = coste * 0.2f;
                } else {
                    descuento = coste * 0.3f;
                }
            }
            total = coste - descuento;
            if (chkContado.isSelected()) {
                incremento = 0f;
            } else {
                incremento = total * 0.15f;
            }
            total = total + incremento;
            txtDescuento.setText(String.valueOf(descuento));//PARA CONVERTIR EL VALOR DE "txtDescuento" A STRING
            txtIncremento.setText(String.valueOf(incremento));
            txtTotal.setText(String.valueOf(total));

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El coste del producto debe ser numerico");
            txtCoste.setText("");//PONE EL CAMPO "COSTE A CERO
            txtCoste.requestFocus();//PARA QUE VUELVA AL CAMPO "COSTE" SI HAY UN ERROR
        }*/
    }//GEN-LAST:event_btnCalcularActionPerformed
    private void calculo() {
        float coste;
        float descuento;
        float total;
        float incremento = 0;
        //try {
        coste = Float.parseFloat(txtCoste.getText());//PARA RECOGER LO QUE TIENES EN ESTA PROPIEDAD
        if (rbAudio.isSelected()) {
            descuento = coste * 0.1f;
        } else {
            if (rbVideo.isSelected()) {//si rbVideo está seleccionado, es decir, si es true
                descuento = coste * 0.2f;
            } else {
                descuento = coste * 0.3f;
            }
        }
        total = coste - descuento;
        if (chkContado.isSelected()) {
            incremento = 0f;
        } else {
            incremento = total * 0.15f;
        }
        total = total + incremento;
        txtDescuento.setText(String.valueOf(descuento));//PARA CONVERTIR EL VALOR DE "txtDescuento" A STRING
        txtIncremento.setText(String.valueOf(incremento));
        txtTotal.setText(String.valueOf(total));

        //} catch (NumberFormatException e) {
        //JOptionPane.showMessageDialog(this, "El coste del producto debe ser numerico");
        //txtCoste.setText("");//PONE EL CAMPO "COSTE A CERO
        //txtCoste.requestFocus();//PARA QUE VUELVA AL CAMPO "COSTE" SI HAY UN ERROR
        //}
    }

    private void txtCosteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCosteFocusLost
        //ESTE MÉTODO DETECTA SI TENEMOS EL CURSOR SOBRE EL CAMPO EN CUESTIÓN O NO
        /*if(!(txtCoste.getText().equals(""))){
            btnCalcular.setEnabled(true);
        }else{
            btnCalcular.setEnabled(false);
        }*/
 /*float coste;
        try {
            coste = Float.parseFloat(txtCoste.getText());
            rbAudio.setEnabled(true);
            rbVideo.setEnabled(true);
            rbLinea.setEnabled(true);
        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this, "El coste del producto debe ser numerico");
            txtCoste.setText("");//PONE EL CAMPO "COSTE A CERO
            rbAudio.setEnabled(false);
            rbVideo.setEnabled(false);
            rbLinea.setEnabled(false);
        }*/
    }//GEN-LAST:event_txtCosteFocusLost

    private void txtCosteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCosteKeyPressed
        //ESTE MÉTODO Se ejecuta cuando el usuario presiona una tecla
        float coste;
        if (!(txtCoste.getText().equals(""))) {
            btnCalcular.setEnabled(true);
            btnLimpiar.setEnabled(true);
            try {
                coste = Float.parseFloat(txtCoste.getText());
                rbAudio.setEnabled(true);
                rbVideo.setEnabled(true);
                rbLinea.setEnabled(true);
            } catch (NumberFormatException e) {

                JOptionPane.showMessageDialog(this, "El coste del producto debe ser numerico");
                txtCoste.setText("");//PONE EL CAMPO "COSTE A CERO
                rbAudio.setEnabled(false);
                rbVideo.setEnabled(false);
                rbLinea.setEnabled(false);
            }
        } else if (txtCoste.getText().equals("")) {
            btnCalcular.setEnabled(false);
            btnLimpiar.setEnabled(false);
        }

    }//GEN-LAST:event_txtCosteKeyPressed

    private void rbLineaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbLineaStateChanged
        //Estos métodos sirven para coger al instante el cambio de dicho
        //botón de tipo "radioButton". Mostrando así al instante el descuento que le correspone
        calculo();
    }//GEN-LAST:event_rbLineaStateChanged

    private void rbAudioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbAudioStateChanged
        calculo();
    }//GEN-LAST:event_rbAudioStateChanged

    private void rbVideoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbVideoStateChanged
        calculo();
    }//GEN-LAST:event_rbVideoStateChanged

    private void txtCosteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCosteKeyReleased
        /*ESTE MÉTODO  Se ejecuta cuando el usuario libera una tecla,es decir,
        cuando soltamos una tecla*/
        float coste;
        if (!(txtCoste.getText().equals(""))) {
            btnCalcular.setEnabled(true);
            btnLimpiar.setEnabled(true);
            try {
                coste = Float.parseFloat(txtCoste.getText());
                rbAudio.setEnabled(true);
                rbVideo.setEnabled(true);
                rbLinea.setEnabled(true);
            } catch (NumberFormatException e) {

                JOptionPane.showMessageDialog(this, "El coste del producto debe ser numerico");
                txtCoste.setText("");//PONE EL CAMPO "COSTE A CERO
                rbAudio.setEnabled(false);
                rbVideo.setEnabled(false);
                rbLinea.setEnabled(false);
            }
        } else if (txtCoste.getText().equals("")) {
            btnCalcular.setEnabled(false);
            btnLimpiar.setEnabled(false);
        }
    }//GEN-LAST:event_txtCosteKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel btnDescuento;
    private javax.swing.ButtonGroup btnGrupo;
    private javax.swing.JLabel btnIncremento;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel btnTotal;
    private javax.swing.JCheckBox chkContado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton rbAudio;
    private javax.swing.JRadioButton rbLinea;
    private javax.swing.JRadioButton rbVideo;
    private javax.swing.JTextField txtCoste;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtIncremento;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
