/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import modelo.Alumno;
import modelo.Asignatura;
import modelo.Curso;
import modelo.Empresa;
import modelo.miModelo;

/**
 *
 * @author Mario-Portatil
 */
public class pnConsultaAlumnos extends javax.swing.JPanel {

    Empresa miEmpresa;
    DefaultComboBoxModel modelo1, modelo3;
    //DefaultTableModel modelo2;
    miModelo modelo2;

    /**
     * Creates new form pnConsultaAlumnos
     */
    public pnConsultaAlumnos(Empresa miEmpresa) {
        initComponents();
        this.miEmpresa = miEmpresa;
        modelo1 = new DefaultComboBoxModel();
        cmbAlumnos.setModel(modelo1);
        /*modelo2 = new DefaultTableModel();
         tblAsignaturas.setModel(modelo2);*/
        String[] titulos = {"CÓDIGO", "NOMBRE"};// Son los titulos que va a tener cada columna.
        modelo2 = new miModelo();
        modelo2.setColumnIdentifiers(titulos);
        tblAsignaturas.setModel(modelo2);
        modelo3 = new DefaultComboBoxModel();
        cmbCursos.setModel(modelo3);
        cargarAlumnos();
    }

    private void cargarAlumnos() {
        ArrayList<Alumno> miAlumno = miEmpresa.getAlumnos();
        for (int i = 0; i < miAlumno.size(); i++) {
            modelo1.addElement(miAlumno.get(i));
        }
    }

    private void cargarCursos() {
        int pos = cmbAlumnos.getSelectedIndex();
        modelo3.removeAllElements();
        /*Cogemos la pos del alumno y todos sus cursos*/
        ArrayList<Curso> misCursos = miEmpresa.getUnAlumno(pos).getMisCursos();
        for (int i = 0; i < misCursos.size(); i++) {
            modelo3.addElement(misCursos.get(i));
        }

        /*ArrayList<Curso> cursos = miEmpresa.getCursos();
        for (int i = 0; i < cursos.size(); i++) {
            modelo1.addElement(cursos.get(i));
        }*/
    }

    private void cargarAsignaturas() {
        ArrayList<Asignatura> asignatura = miEmpresa.getAsignaturas();
        for (int i = 0; i < asignatura.size(); i++) {
            modelo1.addElement(asignatura.get(i));
        }
    }

    public void borrarFilas() {
        int nFilas = modelo2.getRowCount();
        for (int i = 0; i < nFilas; i++) {
            modelo2.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbAlumnos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAsignaturas = new javax.swing.JTable();
        cmbCursos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("CONSULTA DE ALUMNOS");

        cmbAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAlumnosActionPerformed(evt);
            }
        });

        jLabel2.setText("Alumno");

        jLabel3.setText("Curso");

        tblAsignaturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(tblAsignaturas);

        jLabel4.setText("Asignaturas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(45, 45, 45))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(52, 52, 52)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbAlumnos, 0, 151, Short.MAX_VALUE)
                            .addComponent(cmbCursos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(88, 88, 88))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cmbAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAlumnosActionPerformed
        Alumno miAlumno;
        Curso c1;
        miAlumno = (Alumno) cmbAlumnos.getSelectedItem();
        ArrayList<Curso> curso = miAlumno.getMisCursos();
        borrarFilas();
        cargarCursos();
        c1 = (Curso) cmbCursos.getSelectedItem();
        ArrayList<Asignatura> asignatura = c1.getAsignaturas();

        for (int i = 0; i < curso.size(); i++) {
            Curso c = miAlumno.getMisCursos().get(i);/* esto no me devuelve la posición del curso,
             esto ya me devuelve el curso en concreto*/
            for (int a = 0; a < asignatura.size(); a++) {
                Asignatura asig = c1.getAsignaturas().get(i);/* esto no me devuelve la posición de asignatura,
             esto ya me devuelve la asignatura en concreto*/
                String[] datos = new String[modelo2.getColumnCount()];
                datos[0] = c1.getUnaAsignatura(a).getCodigo();
                datos[1] = c1.getUnaAsignatura(a).getDenominacion();
                modelo2.addRow(datos);
            }
        }
    }//GEN-LAST:event_cmbAlumnosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbAlumnos;
    private javax.swing.JComboBox<String> cmbCursos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAsignaturas;
    // End of variables declaration//GEN-END:variables
}
