/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JOptionPane;
import modelo.Empresa;
import modelo.Usuario;

/**
 *
 * @author Mario-Portatil
 */
public class VentanaProfe extends javax.swing.JFrame {

    Empresa miEmpresa;
    Usuario validado;
    pnConsultaAlumnos pConsulta;

    /**
     * Creates new form VentanaProfe
     */

    public VentanaProfe() {
    }

    public VentanaProfe(Empresa miEmpresa, Usuario validado) {
        initComponents();
        this.miEmpresa = miEmpresa;
        this.validado = validado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        miCosultaAlumnos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miDesconectar = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Gestión Académica");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.FlowLayout());

        jMenu2.setText("Alumnos");

        miCosultaAlumnos.setText("Consulta");
        miCosultaAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCosultaAlumnosActionPerformed(evt);
            }
        });
        jMenu2.add(miCosultaAlumnos);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Cerrar");

        miDesconectar.setText("Desconectar");
        miDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDesconectarActionPerformed(evt);
            }
        });
        jMenu3.add(miDesconectar);

        jMenuItem4.setText("Salir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void quitarPaneles() {
        try {
            this.remove(pConsulta);
        } catch (Exception e) {
        }
    }
    private void miDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDesconectarActionPerformed
        this.dispose();
        new Login(miEmpresa).setVisible(true);
        pack();
    }//GEN-LAST:event_miDesconectarActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
         int x = JOptionPane.showConfirmDialog(this, //DEVUELVE UN VALOR ENTERO 
                "¿DESEA SALIR DEL SISTEMA?", // MENSAJE DE CABECERA ENCIMA DE LOS BOTONES
                "SALIR DEL SISTEMA", // BARRA DE TITULO DE LA VENTANA
                JOptionPane.YES_NO_OPTION);     // LOS BOTONES 0 PARA EL CIERRE Y 1 PARA EL NO
        if (x == JOptionPane.YES_OPTION) {    //TAMBIEN ES VALIDO ESTA LINEA PARA EL IF EN VEZ DE EL 0
            //if (x == 0) {
            dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
                int x = JOptionPane.showConfirmDialog(this, //DEVUELVE UN VALOR ENTERO 
                "¿DESEA SALIR DEL SISTEMA?", // MENSAJE DE CABECERA ENCIMA DE LOS BOTONES
                "SALIR DEL SISTEMA", // BARRA DE TITULO DE LA VENTANA
                JOptionPane.YES_NO_OPTION);     // LOS BOTONES 0 PARA EL CIERRE Y 1 PARA EL NO
        if (x == JOptionPane.YES_OPTION) {    //TAMBIEN ES VALIDO ESTA LINEA PARA EL IF EN VEZ DE EL 0
            //if (x == 0) {
            dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void miCosultaAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCosultaAlumnosActionPerformed
         quitarPaneles();
        pConsulta = new pnConsultaAlumnos(miEmpresa);
        getContentPane().add(pConsulta);
        pack();
    }//GEN-LAST:event_miCosultaAlumnosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaProfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaProfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaProfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaProfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaProfe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem miCosultaAlumnos;
    private javax.swing.JMenuItem miDesconectar;
    // End of variables declaration//GEN-END:variables
}
