/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.Correo;
import modelo.Empresa;
import modelo.Fecha;
import modelo.Usuario;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author 203pc19
 */
public class pnEnviar extends javax.swing.JPanel {

    DefaultComboBoxModel modelo;
    Empresa miEmpresa;
    Usuario validado;
    pnEnviar pEnviar;

    /**
     * Creates new form pnEnviar
     */
    public pnEnviar(Empresa miEmpresa, Usuario validado) {
        initComponents();
        modelo = new DefaultComboBoxModel();
        cmbDestinatario.setModel(modelo);
        this.miEmpresa = miEmpresa;
        this.validado = validado;
        cargarDestinatarios();
        Fecha f = new Fecha();
        txtFecha.setText(f.visualizar());
    }

    private void cargarDestinatarios() {//me carga todos los usuarios en el comboBox
        /*Lista de arrays que son de tipo Usuario(<Usuario>) y lo llamamos "usuarios"*/
        ArrayList<Usuario> usuarios = miEmpresa.getUsuarios();
        for (int i = 0; i < usuarios.size(); i++) {
            modelo.addElement(usuarios.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbDestinatario = new javax.swing.JComboBox();
        txtFecha = new javax.swing.JTextField();
        txtAsunto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taTexto = new javax.swing.JTextArea();
        btnEnviar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        jLabel1.setText("ENVIAR MENSAJES");

        jLabel2.setText("DESTINATARIO");

        jLabel3.setText("FECHA");

        jLabel4.setText("ASUNTO");

        jLabel5.setText("TEXTO");

        txtFecha.setEditable(false);

        taTexto.setColumns(20);
        taTexto.setRows(5);
        jScrollPane1.setViewportView(taTexto);

        btnEnviar.setText("ENVIAR");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(btnEnviar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGap(53, 53, 53)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbDestinatario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFecha)
                                .addComponent(txtAsunto)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar)
                    .addComponent(btnCancelar))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        String fecha, asunto, texto;
        Usuario destinatario;
        fecha = txtFecha.getText();
        asunto = txtAsunto.getText().trim();// el trim elimina los espacios en blanco de ambos extremos del string
        texto = taTexto.getText().trim();
        destinatario = (Usuario) cmbDestinatario.getSelectedItem();
        if (asunto.equals("")) {// si está vacio...
            int x = JOptionPane.showConfirmDialog(this, //DEVUELVE UN VALOR ENTERO 
                    "No tienes asunto, ¿Deseas incluirlo?", // MENSAJE DE CABECERA ENCIMA DE LOS BOTONES
                    "Asunto vacio", // BARRA DE TITULO DE LA VENTANA
                    JOptionPane.YES_NO_OPTION); // LOS BOTONES 0 PARA EL CIERRE Y 1 PARA EL NO
            if (x == 0) {// ese if es igual que este if(x==JOptionPane.YES_OPTION)
                txtAsunto.requestFocus();
            } else {//si la respuesta es no...
                //Metemos todo en un método par ahorrar código
                envio(fecha, asunto, texto, destinatario);

                /*texto = taTexto.getText().trim();
                 //validado es quien envia el correo
                 Correo c = new Correo(fecha, asunto, texto, validado);
                 destinatario = (Usuario) cmbDestinatario.getSelectedItem();
                 destinatario.getbEntrada().add(c);// así se envia el correo al destinaratio*/
                //y se le añade a su bandeja de entrada
            }
        } else {
            //Metemos todo en un método par ahorrar código
            envio(fecha, asunto, texto, destinatario);

            /*texto = taTexto.getText().trim();
             //validado es quien envia el correo
             Correo c = new Correo(fecha, asunto, texto, validado);
             destinatario = (Usuario) cmbDestinatario.getSelectedItem();
             destinatario.getbEntrada().add(c);// así se envia el correo al destinaratio
             //y se le añade a su bandeja de entrada*/
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed
    private void envio(String fecha, String asunto, String texto, Usuario destinatario) {
        Correo c = new Correo(fecha, asunto, texto, validado);
        destinatario.getbEntrada().add(c);// así se envia el correo al destinaratio*/
                //y se le añade a su bandeja de entrada
        limpiar();
    }

    private void limpiar() {
        taTexto.setText("");
        txtAsunto.setText("");
        cmbDestinatario.setSelectedIndex(0);//me vuelve a la posición por defecto
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JComboBox cmbDestinatario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taTexto;
    private javax.swing.JTextField txtAsunto;
    private javax.swing.JTextField txtFecha;
    // End of variables declaration//GEN-END:variables
}
