/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.Conexion;
import controlador.GestorTablaAcademia;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Academia;

/**
 *
 * @author Mario
 */
public class PnConsultarAcademia extends javax.swing.JPanel {

    Conexion bd;
    DefaultTableModel modeloTabla;
    GestorTablaAcademia tabla;

    /**
     * Creates new form PnConsultarAcademia
     */
    public PnConsultarAcademia() {
        initComponents();
        bd = new Conexion();
        int resultado = bd.establecer("jdbc:mysql://localhost:3306/programacion");// lo último es el nombre de la base de datos
        if (resultado != 0) {
            JOptionPane.showMessageDialog(this, "CONEXIÓN INCORRECTA");
            System.exit(0);
        }
        modeloTabla = new DefaultTableModel();
        String[] titulos = {"Nombre", "CIF", "Dirección", "Población", "teléfono", "Email"};
        modeloTabla.setColumnIdentifiers(titulos);
        tblAcademia.setModel(modeloTabla);
        tabla = new GestorTablaAcademia(bd);
        cargarAcademias();
        bd.cerrar();
    }

    private void cargarAcademias() {
        ArrayList<Academia> academias;
        academias = tabla.consultaTodasAcademias();
        for (int i = 0; i < academias.size(); i++) {
            Vector v = new Vector();
            v.add(academias.get(i).getNombre());
            v.add(academias.get(i).getCif());
            v.add(academias.get(i).getDireccion());
            v.add(academias.get(i).getPoblacion());
            v.add(academias.get(i).getTelefono());
            v.add(academias.get(i).getEmail());
            /*v.removeElementAt(i);*/
            modeloTabla.addRow(v);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAcademia = new javax.swing.JTable();

        jLabel1.setText("CONSULTA DE ACADEMIAS");

        tblAcademia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAcademia);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAcademia;
    // End of variables declaration//GEN-END:variables
}
