/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.Conexion;
import controlador.GestorTablaAcademia;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Academia;

/**
 *
 * @author Mario
 */
public class PnModificarAcademia extends javax.swing.JPanel {

    private Conexion bd;
    DefaultComboBoxModel modelo;
    Academia miAcademia;
    String cif;
    String telefonoActual = "";
    String emailActual = "";
    String telefonoAntiguo = "";
    String emailAntiguo = "";

    /**
     * Creates new form PnModificarAcademia
     */
    public PnModificarAcademia() {
        initComponents();
        bd = new Conexion();
        modelo = new DefaultComboBoxModel();
        cmbAcademia.setModel(modelo);
        int resultado = bd.establecer("jdbc:mysql://localhost:3306/programacion");// lo último es el nombre de la base de datos
        if (resultado != 0) {
            JOptionPane.showMessageDialog(this, "CONEXIÓN INCORRECTA");
            System.exit(0);
        }
        cargarAcademias();
    }

    private void cargarAcademias() {
        GestorTablaAcademia a = new GestorTablaAcademia(bd);
        ArrayList<Academia> academias;
        //lo hago así por un comboBox no es compatible con la clase GestorTablaAcademia
        academias = a.consultaTodasAcademias();
        for (int i = 0; i < academias.size(); i++) {
            modelo.addElement(academias.get(i));
        }
        //cmbAcademia.setSelectedIndex(0);//así le digo que empieze en la posicion 0
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTelefonoNuevo = new javax.swing.JTextField();
        txtEmailNuevo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTelefonoActual = new javax.swing.JTextField();
        txtEmailActual = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmbAcademia = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        jLabel6.setText("TELÉFONO NUEVO");

        jLabel7.setText("EMAIL NUEVO");

        btnAceptar.setText("ACEPTAR");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel8.setText("TELÉFONO ACTUAL");

        jLabel9.setText("EMAIL ACTUAL");

        txtTelefonoActual.setEditable(false);

        txtEmailActual.setEditable(false);

        jLabel1.setText("MODIFICACIÓN DE ACADEMIAS");

        cmbAcademia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAcademiaActionPerformed(evt);
            }
        });

        jLabel2.setText("ACADEMIA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTelefonoActual)
                                    .addComponent(txtEmailActual, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addComponent(btnAceptar)
                                    .addGap(62, 62, 62)
                                    .addComponent(btnCancelar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                    .addGap(40, 40, 40)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtTelefonoNuevo)
                                        .addComponent(txtEmailNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(71, 71, 71))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(37, 37, 37)
                                .addComponent(cmbAcademia, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAcademia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTelefonoActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtEmailActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTelefonoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEmailNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAcademiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAcademiaActionPerformed
        comboBoxAcademia();
    }//GEN-LAST:event_cmbAcademiaActionPerformed

    public void comboBoxAcademia() {
        if (telefonoAntiguo.compareToIgnoreCase(telefonoActual) != 0
                && emailAntiguo.compareToIgnoreCase(emailActual) != 0) {
            modelo.removeAllElements();
            cargarAcademias();
            telefonoActual = "";
            emailActual = "";
            telefonoAntiguo = "";
            emailAntiguo = "";
        }
        miAcademia = (Academia) modelo.getSelectedItem();

        txtTelefonoActual.setText(miAcademia.getTelefono());
        txtEmailActual.setText(miAcademia.getEmail());
    }


    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        miAcademia = (Academia) modelo.getSelectedItem();
        cif = miAcademia.getCif();
        Academia a;
        String telefonoNuevo, emailNuevo;
        telefonoNuevo = txtTelefonoNuevo.getText();
        emailNuevo = txtEmailNuevo.getText();
        telefonoAntiguo = miAcademia.getTelefono();//ME DA EL TELEFONO ANTES DE MODIFICARLO
        emailAntiguo = miAcademia.getEmail();//ME DA EL EMAIL ANTES DE MODIFICARLO
        /*GestorTablaAcademia migestor2 = new GestorTablaAcademia(bd);
        cif = miAcademia.getCif();
        a2 = migestor2.existeUnaAcademia(cif);*/

        if (telefonoNuevo.length() != 0 && emailNuevo.length() != 0) {
            telefonoActual = telefonoNuevo;//ME DA EL TELEFONO YA MODIFICADO
            emailActual = emailNuevo;//ME DA EL EMAIL YA MODIFICADO
            if (telefonoAntiguo.compareToIgnoreCase(telefonoActual) == 0
                    || emailAntiguo.compareToIgnoreCase(emailActual) == 0) {
                JOptionPane.showMessageDialog(this, "EL TELEFONO O EL EMAIL NUEVOS COINCIDEN CON LOS ANTIGUOS");
                limpiar();
            } else {
                a = new Academia(cif, telefonoNuevo, emailNuevo);
                GestorTablaAcademia migestor = new GestorTablaAcademia(bd);
                int registros = migestor.actualizarRegistros(a);
                if (registros != 0) {
                    JOptionPane.showMessageDialog(this, "ACADEMIA MODIFICADA");
                    limpiar();
                    //comboBoxAcademia();
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "HAY CAMPOS VACIOS");
        }

        cmbAcademia.setSelectedIndex(0);//así le digo que empieze en la posicion 0
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    public void limpiar() {
        txtTelefonoNuevo.setText("");
        txtEmailNuevo.setText("");
    }

    /*private String visualizarTelefono(Academia a) {
        return a.getTelefono();
    }

    private String visualizarEmail(Academia a) {
        return a.getEmail();
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cmbAcademia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtEmailActual;
    private javax.swing.JTextField txtEmailNuevo;
    private javax.swing.JTextField txtTelefonoActual;
    private javax.swing.JTextField txtTelefonoNuevo;
    // End of variables declaration//GEN-END:variables
}
