/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.Conexion;
import controlador.GestorTablaAlumno;
import controlador.GestorTablaCurso;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Alumno;
import modelo.Curso;

/**
 *
 * @author Mario
 */
public class PnModificarAlumno extends javax.swing.JPanel {

    private Conexion bd;
    DefaultComboBoxModel modeloAlumnos;
    DefaultComboBoxModel modeloCursos;
    Curso miCurso;
    Alumno miAlumno;
    String codCursoNuevo = "";
    String codCursoAlumnoActual = "";
    int codAlumno;
    int registros = 0;

    /**
     * Creates new form PnModificarAlumno
     */
    public PnModificarAlumno() {
        initComponents();
        bd = new Conexion();
        modeloAlumnos = new DefaultComboBoxModel();
        cmbAlumnos.setModel(modeloAlumnos);
        modeloCursos = new DefaultComboBoxModel();
        cmbCursos.setModel(modeloCursos);
        int resultado = bd.establecer("jdbc:mysql://localhost:3306/programacion");// lo último es el nombre de la base de datos
        if (resultado != 0) {
            JOptionPane.showMessageDialog(this, "CONEXIÓN INCORRECTA");
            System.exit(0);
        }
        cargarAlumnos();
        cargarCursos();
    }

    private void cargarCursos() {
        GestorTablaCurso c = new GestorTablaCurso(bd);
        ArrayList<Curso> cursos;
        //lo hago así por un comboBox no es compatible con la clase GestorTablaCursos
        cursos = c.consultaTodosCursos();
        for (int i = 0; i < cursos.size(); i++) {
            modeloCursos.addElement(cursos.get(i));
        }
        /*modeloCursos.insertElementAt("------", 0);
        cmbCursos.setSelectedIndex(0);*/
    }

    private void cargarAlumnos() {
        GestorTablaAlumno a = new GestorTablaAlumno(bd);
        ArrayList<Alumno> alumnos;
        //lo hago así por un comboBox no es compatible con la clase GestorTablaAcademia
        alumnos = a.consultaTodosAlumnos();
        for (int i = 0; i < alumnos.size(); i++) {
            modeloAlumnos.addElement(alumnos.get(i));
        }
    }

    public void comboBoxAlumno() {
        if (registros > 0) {
            cmbAlumnos.removeAllItems();
            if (modeloAlumnos.getSize() == 0) {
                cargarAlumnos();
            }
            registros = 0;
        } else {
            miAlumno = (Alumno) modeloAlumnos.getSelectedItem();

            txtCursoActual.setText(miAlumno.getCodCurso());
            //codCursoAlumnoActual = txtCursoActual.getText();
            txtIdAlumno.setText(Integer.toString(miAlumno.getCodAlumno()));
            codAlumno = Integer.parseInt(txtIdAlumno.getText());
        }
    }

    public void comboBoxCurso() {
        miCurso = (Curso) cmbCursos.getSelectedItem();

        txtCursoNuevo.setText(miCurso.getCodCurso());
        codCursoNuevo = txtCursoNuevo.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtCursoActual = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCursoNuevo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbAlumnos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbCursos = new javax.swing.JComboBox<>();
        txtIdAlumno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        cmbAceptar.setText("ACEPTAR");
        cmbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");

        jLabel1.setText("MODIFICAR ALUMNOS");

        jLabel2.setText("ALUMNOS");

        cmbAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAlumnosActionPerformed(evt);
            }
        });

        jLabel3.setText("CURSO ACTUAL");

        jLabel4.setText("CURSO NUEVO");

        jLabel5.setText("CURSOS");

        cmbCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCursosActionPerformed(evt);
            }
        });

        jLabel6.setText("ID ALUMNO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(cmbAceptar)
                        .addGap(76, 76, 76)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addComponent(txtIdAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbCursos, 0, 155, Short.MAX_VALUE)
                                    .addComponent(txtCursoNuevo)
                                    .addComponent(txtCursoActual, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(38, 38, 38)
                                .addComponent(cmbAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cmbAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCursoActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCursoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAceptar)
                    .addComponent(btnCancelar))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAceptarActionPerformed
        Alumno a;

        GestorTablaCurso c = new GestorTablaCurso(bd);
        int nPlazasOcu = 0, nPlazasLibres = 0, nPlazasCursoTotales = 0;
        codCursoAlumnoActual = txtCursoActual.getText();//PARA CONTROLAR QUE NO ELIGA EL MISMO CURSO

        if (codCursoAlumnoActual.compareTo(codCursoNuevo) == 0) {
            JOptionPane.showMessageDialog(this, "ES EL MISMO CURSO");
        } else {
            nPlazasOcu = c.AlumnosPorCurso(codCursoNuevo);
            nPlazasCursoTotales = c.plazasCurso(codCursoNuevo);// ME DEVUELVE LAS PLAZAS TOTALES QUE TIENE EL CURSO NUEVO AL QUE SE QUIERE CAMBIAR
            nPlazasLibres = nPlazasCursoTotales - nPlazasOcu;// ME DEVUELVE LAS PLAZAS LIBRES QUE TIENE EL CURSO
            if (nPlazasOcu == nPlazasCursoTotales) {
                JOptionPane.showMessageDialog(this, "NO QUEDAN PLAZAS PARA ESTE CURSO");
            } else {
                a = new Alumno(codAlumno, codCursoNuevo);
                GestorTablaAlumno migestor = new GestorTablaAlumno(bd);
                registros = migestor.actualizarRegistros(a);
                if (registros != 0) {
                    JOptionPane.showMessageDialog(this, "ALUMNO MODIFICADO");
                    comboBoxAlumno();
                }
            }
        }

    }//GEN-LAST:event_cmbAceptarActionPerformed

    private void cmbAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAlumnosActionPerformed
        comboBoxAlumno();
    }//GEN-LAST:event_cmbAlumnosActionPerformed

    private void cmbCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCursosActionPerformed
        comboBoxCurso();
    }//GEN-LAST:event_cmbCursosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton cmbAceptar;
    private javax.swing.JComboBox<String> cmbAlumnos;
    private javax.swing.JComboBox<String> cmbCursos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCursoActual;
    private javax.swing.JTextField txtCursoNuevo;
    private javax.swing.JTextField txtIdAlumno;
    // End of variables declaration//GEN-END:variables
}
