/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import modelo.Agenda;
import modelo.Empresa;
import modelo.Fecha;
import modelo.Usuario;

/**
 *
 * @author Mario
 */
public class pnConsultarEventUser extends javax.swing.JPanel {

    Usuario validado;
    Empresa miEmpresa;
    //Agenda miEvento;
    Fecha f;
    DefaultComboBoxModel modeloMes;
    DefaultComboBoxModel modeloEvento;
    DefaultComboBoxModel modeloDias;

    /**
     * Creates new form pnConsultarEventUser
     */
    public pnConsultarEventUser(Usuario validado, Empresa miEmpresa) {
        initComponents();
        this.validado = validado;
        this.miEmpresa = miEmpresa;
        modeloMes = new DefaultComboBoxModel();
        cmbMeses.setModel(modeloMes);
        modeloEvento = new DefaultComboBoxModel();
        cmbNomEvento.setModel(modeloEvento);
        modeloDias = new DefaultComboBoxModel();
        cmbDia.setModel(modeloDias);
        //cargarEventos();
        //cargarDias();
        cargarMeses();
    }

    private void cargarEventos() {//me carga todos los eventos en el comboBox
        /* ArrayList<Agenda> miAgenda = validado.getbEntrada();
         for (int i = 0; i < miAgenda.size(); i++) {
         //Agenda a = miAgenda.get(i);
         modeloEvento.addElement(miAgenda.get(i));*/

        String delimitacionesFecha2 = "/";
        String[] separadas3;
        String fechita;
        for (int i = 0; i < validado.getbEntrada().size(); i++) {
            fechita = validado.getbEntrada().get(i).getFecha();
            separadas3 = fechita.split(delimitacionesFecha2);
            if (Integer.parseInt(separadas3[1]) == cmbMeses.getSelectedIndex() + 1) {
                modeloEvento.removeAllElements();
                modeloEvento.addElement(validado.getbEntrada().get(i));
            }
        }

    }

    public void cargarDias() {
        int a;
        int mes = cmbMeses.getSelectedIndex() + 1;
        modeloDias.removeAllElements();
        if (mes == 1 | mes == 3 | mes == 5 | mes == 7 | mes == 8 | mes == 10 | mes == 12) {

            for (a = 0; a < 31; a++) {
                modeloDias.addElement(a + 1);
            }
        } else if (mes == 4 | mes == 6 | mes == 9 | mes == 11) {
            for (a = 0; a < 30; a++) {
                modeloDias.addElement(a + 1);
            }
        } else if (mes == 2) {
            for (a = 0; a < 28; a++) {
                modeloDias.addElement(a + 1);
            }
        }
        modeloDias.insertElementAt("------", 0);//asi se inserta un elemento en la posicion que le digamos
        cmbDia.setSelectedIndex(0);//asi decimos que el combo empiece en la posicion "0"
    }

    public void cargarMeses() {
        modeloMes.addElement("Enero");
        modeloMes.addElement("Febrero");
        modeloMes.addElement("Marzo");
        modeloMes.addElement("Abril");
        modeloMes.addElement("Mayo");
        modeloMes.addElement("Junio");
        modeloMes.addElement("Julio");
        modeloMes.addElement("Agosto");
        modeloMes.addElement("Septiembre");
        modeloMes.addElement("Octubre");
        modeloMes.addElement("Noviembre");
        modeloMes.addElement("Diciembre");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtFecha = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescripcion = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbNomEvento = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cmbMeses = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        cmbDia = new javax.swing.JComboBox();

        jLabel1.setText("AGENDA DE EVENTOS");

        txtHora.setEditable(false);

        btnAceptar.setText("ACEPTAR");

        btnCancelar.setText("CANCELAR");

        txtFecha.setEditable(false);

        taDescripcion.setEditable(false);
        taDescripcion.setColumns(20);
        taDescripcion.setRows(5);
        jScrollPane1.setViewportView(taDescripcion);

        jLabel3.setText("NOMBRE EVENTO");

        jLabel4.setText("FECHA");

        jLabel5.setText("DESCRIPCIÓN");

        jLabel6.setText("HORA");

        cmbNomEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNomEventoActionPerformed(evt);
            }
        });

        jLabel2.setText("MES");

        cmbMeses.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero, Febrero, Marzo, Abril, Mayo, Junio, Julio, Agosto, Septiembre, Octubre, Noviembre, Diciembre" }));
        cmbMeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMesesActionPerformed(evt);
            }
        });

        jLabel7.setText("DÍA");

        cmbDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtHora, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbNomEvento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cmbMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbDia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelar)))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbNomEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbNomEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNomEventoActionPerformed

        String fecha, hora, descripcion, fechita;
        Agenda miAgenda;
        if (modeloEvento.getSize() > 0) {
            miAgenda = (Agenda) modeloEvento.getSelectedItem();
            fecha = miAgenda.getFecha();
            hora = miAgenda.getHora();
            descripcion = miAgenda.getDescripcion();

            txtFecha.setText(fecha);
            txtHora.setText(hora);
            taDescripcion.setText(descripcion);
        } else {
            txtFecha.setText("");
            txtHora.setText("");
            taDescripcion.setText("");
        }
    }//GEN-LAST:event_cmbNomEventoActionPerformed

    private void cmbMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMesesActionPerformed

        String fecha, hora, descripcion, fechita = "";

        String delimitacionesFecha2 = "/";
        String[] separadas3;

        modeloEvento.removeAllElements();
//cargarEventos();
        modeloEvento.removeAllElements();
        txtFecha.setText("");
        txtHora.setText("");
        taDescripcion.setText("");
        for (int i = 0; i < validado.getbEntrada().size(); i++) {
            fechita = validado.getbEntrada().get(i).getFecha();
            separadas3 = fechita.split(delimitacionesFecha2);
            /*if (modeloEvento.getSize() > 0 && Integer.parseInt(separadas3[1]) != cmbMeses.getSelectedIndex() + 1) {
             modeloEvento.removeAllElements();
             }*/

 /*if (Integer.parseInt(separadas3[1]) == cmbMeses.getSelectedIndex() + 1
                    && Integer.parseInt(separadas3[0]) == cmbDia.getSelectedIndex() + 1) {
                modeloEvento.addElement(validado.getbEntrada().get(i));
            }*/
            if (Integer.parseInt(separadas3[1]) == cmbMeses.getSelectedIndex() + 1
                    && Integer.parseInt(separadas3[0]) == cmbDia.getSelectedIndex() + 1) {
                modeloEvento.addElement(validado.getbEntrada().get(i));
            } else if (Integer.parseInt(separadas3[1]) == cmbMeses.getSelectedIndex() + 1
                    && modeloDias.getElementAt(0) == cmbDia.getSelectedItem()/*cmbDia.getSelectedIndex()==0*/) {
                modeloEvento.addElement(validado.getbEntrada().get(i));

            }
            /*if(Integer.parseInt(separadas3[1]) == cmbMeses.getSelectedIndex() + 1
                    &&uno.compareToIgnoreCase(cmbDia.getSelectedItem().toString())==0){
                modeloEvento.addElement(validado.getbEntrada().get(i));
        
             }*/
        }
        cargarDias();

    }//GEN-LAST:event_cmbMesesActionPerformed

    private void cmbDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDiaActionPerformed
        String fecha, hora, descripcion, fechita = "";
        String delimitacionesFecha2 = "/";
        String[] separadas3;
        modeloEvento.removeAllElements();
        txtFecha.setText("");
        txtHora.setText("");
        taDescripcion.setText("");
        for (int i = 0; i < validado.getbEntrada().size(); i++) {
            fechita = validado.getbEntrada().get(i).getFecha();
            separadas3 = fechita.split(delimitacionesFecha2);
            /*if (modeloEvento.getSize() > 0 && Integer.parseInt(separadas3[1]) != cmbMeses.getSelectedIndex() + 1) {
             modeloEvento.removeAllElements();
             }*/

 /*if (Integer.parseInt(separadas3[0]) == cmbDia.getSelectedIndex() + 1
                    && Integer.parseInt(separadas3[1]) == cmbMeses.getSelectedIndex() + 1) {
                modeloEvento.addElement(validado.getbEntrada().get(i));
            }*/
            if (Integer.parseInt(separadas3[1]) == cmbMeses.getSelectedIndex() + 1
                    && Integer.parseInt(separadas3[0]) == cmbDia.getSelectedIndex()) {
                modeloEvento.addElement(validado.getbEntrada().get(i));
            } else if (Integer.parseInt(separadas3[1]) == cmbMeses.getSelectedIndex() + 1
                    && modeloDias.getElementAt(0) == cmbDia.getSelectedItem()/*cmbDia.getSelectedIndex()==0*/) {
                modeloEvento.addElement(validado.getbEntrada().get(i));

            }
        }
    }//GEN-LAST:event_cmbDiaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox cmbDia;
    private javax.swing.JComboBox cmbMeses;
    private javax.swing.JComboBox cmbNomEvento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taDescripcion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    // End of variables declaration//GEN-END:variables
}
