/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Empresa;
import modelo.Usuario;

/**
 *
 * @author Mario
 */
public class pnModificarEmpleado extends javax.swing.JPanel {

    Empresa miEmpresa;
    Usuario user;
    DefaultComboBoxModel modelo;//del comboBox

    /**
     * Creates new form pnModificarAdmin
     */
    public pnModificarEmpleado(Empresa miEmpresa) {
        initComponents();
        this.miEmpresa = miEmpresa;
        modelo = new DefaultComboBoxModel();
        cmbEmpleados.setModel(modelo);
        cargarDestinatarios();
    }

    private void cargarDestinatarios() {//me carga todos los usuarios en el comboBox
        /*Lista de arrays que son de tipo Usuario(<Usuario>) y lo llamamos "usuarios"*/
        ArrayList<Usuario> users = miEmpresa.getUsuarios();
        for (int i = 0; i < users.size(); i++) {
            modelo.addElement(users.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbEmpleados = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPassViejo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPassNuevo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPassNuevo2 = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();

        jLabel1.setText("MODIFICAR EMPLEADOS");

        jLabel2.setText("EMPLEADOS");

        jLabel3.setText("CONTRASEÑA ACTUAL");

        txtPassViejo.setEditable(false);

        jLabel4.setText("CONTRASEÑA NUEVA");

        jLabel5.setText("CONTRASEÑA NUEVA");

        btnAceptar.setText("ACEPTAR");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnVer.setText("VER");
        btnVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVerMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnVerMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPassNuevo2)
                            .addComponent(txtPassNuevo)
                            .addComponent(cmbEmpleados, 0, 169, Short.MAX_VALUE)
                            .addComponent(txtPassViejo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVer))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPassViejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVer))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPassNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPassNuevo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String passNuevo;
        Usuario user;
        String texto = "";
        String valor = new String(txtPassNuevo.getText());
        //Pasamos ambos txtPassNuevo a un String para poder comprarlos despues
        String valor2 = new String(txtPassNuevo2.getText());
        if (valor.length() == 0 || valor2.length() == 0) {
            JOptionPane.showMessageDialog(this, "CONTRASEÑA OBLIGATORIO");
        } else if (valor.compareToIgnoreCase(valor2) != 0) {
            JOptionPane.showMessageDialog(this, "La contraseña nueva no coincide");
            txtPassNuevo.setText("");
            txtPassNuevo2.setText("");
        } else {
            passNuevo = txtPassNuevo2.getText();
            user = (Usuario) cmbEmpleados.getSelectedItem();
            user.setPassword(passNuevo);
            JOptionPane.showMessageDialog(this, "CONTRASEÑA CAMBIADA");
            limpiar();
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnVerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMousePressed
        String passViejo;
        Usuario user;
        user = (Usuario) modelo.getSelectedItem();
        passViejo = user.getPassword();
        txtPassViejo.setText(passViejo);
    }//GEN-LAST:event_btnVerMousePressed

    private void btnVerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMouseReleased
        txtPassViejo.setText("");
    }//GEN-LAST:event_btnVerMouseReleased

    private void limpiar() {
        txtPassNuevo.setText("");
        txtPassNuevo2.setText("");
        txtPassViejo.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnVer;
    private javax.swing.JComboBox<String> cmbEmpleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtPassNuevo;
    private javax.swing.JTextField txtPassNuevo2;
    private javax.swing.JTextField txtPassViejo;
    // End of variables declaration//GEN-END:variables
}
