/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JOptionPane;
import modelo.Empresa;
import modelo.Usuario;

/**
 *
 * @author Mario
 */
public class VentanaAdmin extends javax.swing.JFrame {

    Empresa miEmpresa;
    Usuario validado;
    pnAltaEmpleado pAlta;
    pnBajaEmpleado pBaja;
    pnModificarEmpleado pModEmpleado;
    pnInsertarEventAdmin pInsetarEnvent;
    VentanaPrincipal vPrincipal;

    /**
     * Creates new form VentanaAdmin
     */
    public VentanaAdmin() {
        initComponents();
    }

    public VentanaAdmin(Empresa miEmpresa, Usuario validado) {
        initComponents();
        this.miEmpresa = miEmpresa;
        this.validado = validado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miAlta = new javax.swing.JMenuItem();
        miBaja = new javax.swing.JMenuItem();
        miModificar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miInsertar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miCerrarSesion = new javax.swing.JMenuItem();
        miSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.FlowLayout());

        jMenu1.setText("Empleados");

        miAlta.setText("Dar de Alta");
        miAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAltaActionPerformed(evt);
            }
        });
        jMenu1.add(miAlta);

        miBaja.setText("Dar de Baja");
        miBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBajaActionPerformed(evt);
            }
        });
        jMenu1.add(miBaja);

        miModificar.setText("Modificar Empleados");
        miModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miModificarActionPerformed(evt);
            }
        });
        jMenu1.add(miModificar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Agenda");

        miInsertar.setText("Insertar Evento");
        miInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miInsertarActionPerformed(evt);
            }
        });
        jMenu2.add(miInsertar);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Salir");

        miCerrarSesion.setText("Cerrar Sesion");
        miCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCerrarSesionActionPerformed(evt);
            }
        });
        jMenu3.add(miCerrarSesion);

        miSalir.setText("Salir de la Aplicación");
        miSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalirActionPerformed(evt);
            }
        });
        jMenu3.add(miSalir);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCerrarSesionActionPerformed

        //new Login(miEmpresa).setVisible(true);
        //vPrincipal.setVisible(true);
        new VentanaPrincipal(miEmpresa).setVisible(true);//Así abrimos la ventana de nuevo

        this.dispose();
        pack();
    }//GEN-LAST:event_miCerrarSesionActionPerformed

    private void miAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAltaActionPerformed
        quitarPaneles();
        pAlta = new pnAltaEmpleado(miEmpresa);
        getContentPane().add(pAlta);
        pack();
    }//GEN-LAST:event_miAltaActionPerformed

    private void miBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBajaActionPerformed
        quitarPaneles();
        pBaja = new pnBajaEmpleado(miEmpresa);
        getContentPane().add(pBaja);
        pack();
    }//GEN-LAST:event_miBajaActionPerformed

    private void miModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miModificarActionPerformed
        quitarPaneles();
        pModEmpleado = new pnModificarEmpleado(miEmpresa);
        getContentPane().add(pModEmpleado);
        pack();
    }//GEN-LAST:event_miModificarActionPerformed

    private void miInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miInsertarActionPerformed
        quitarPaneles();
        pInsetarEnvent = new pnInsertarEventAdmin(miEmpresa, validado);
        getContentPane().add(pInsetarEnvent);
        pack();
    }//GEN-LAST:event_miInsertarActionPerformed

    private void miSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirActionPerformed
        int x = JOptionPane.showConfirmDialog(this, //DEVUELVE UN VALOR ENTERO 
                "¿DESEA SALIR DEL SISTEMA?", // MENSAJE DE CABECERA ENCIMA DE LOS BOTONES
                "SALIR DEL SISTEMA", // BARRA DE TITULO DE LA VENTANA
                JOptionPane.YES_NO_OPTION);     // LOS BOTONES 0 PARA EL CIERRE Y 1 PARA EL NO
        if (x == JOptionPane.YES_OPTION) {    //TAMBIEN ES VALIDO ESTA LINEA PARA EL IF EN VEZ DE EL 0
            //if (x == 0) {
            dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_miSalirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int x = JOptionPane.showConfirmDialog(this,"¿DESEA SALIR DEL SISTEMA?",
                "SALIR DEL SISTEMA",JOptionPane.YES_NO_OPTION);// LOS BOTONES 0 PARA EL CIERRE Y 1 PARA EL NO
        if (x == JOptionPane.YES_OPTION) {    //TAMBIEN ES VALIDO ESTA LINEA PARA EL IF EN VEZ DE EL 0
            //if (x == 0) {
            dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void quitarPaneles() {
        try {
            this.remove(pAlta);
        } catch (Exception e) {
        }
        try {
            this.remove(pBaja);
        } catch (Exception e) {
        }
        try {
            this.remove(pModEmpleado);
        } catch (Exception e) {
        }
        try {
            this.remove(pInsetarEnvent);
        } catch (Exception e) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miAlta;
    private javax.swing.JMenuItem miBaja;
    private javax.swing.JMenuItem miCerrarSesion;
    private javax.swing.JMenuItem miInsertar;
    private javax.swing.JMenuItem miModificar;
    private javax.swing.JMenuItem miSalir;
    // End of variables declaration//GEN-END:variables
}
