/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JOptionPane;
import modelo.Empresa;
import modelo.Libros;
import modelo.Usuario;

/**
 *
 * @author 203pc19
 */
public class Biblioteca extends javax.swing.JFrame {

    pnBienvenida pBienvenida;
    pnAltaUsuarios pAlta;
    pnPrestamos pPrestamos;
    pnConsultas pConsultas;
    Empresa miEmpresa;

    public Biblioteca() {
        initComponents();
        miEmpresa = new Empresa();//Lo creamos para utilizarlo en AltaUsuario
        anadirBienvenida();
    }

    private void anadirBienvenida() {
        pBienvenida = new pnBienvenida();
        this.getContentPane().add(pBienvenida);
        pack();
    }

    private void quitarPaneles() {
        try {
            remove(pBienvenida);
        } catch (Exception ex) {
        }
        try {
            remove(pAlta);
        } catch (Exception ex) {
        }
        try {
            remove(pPrestamos);
        } catch (Exception ex) {
        }
        try {
            remove(pConsultas);
        } catch (Exception ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnUsuario = new javax.swing.JMenu();
        miUserNuevo = new javax.swing.JMenuItem();
        miPrestamo = new javax.swing.JMenuItem();
        mnLibros = new javax.swing.JMenu();
        miLibrosPrestados = new javax.swing.JMenuItem();
        mnSalir = new javax.swing.JMenu();
        miSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("GESTIÓN DE ALQUILERES");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.FlowLayout());

        mnUsuario.setText("Usuario");

        miUserNuevo.setText("Usuario Nuevo");
        miUserNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUserNuevoActionPerformed(evt);
            }
        });
        mnUsuario.add(miUserNuevo);

        miPrestamo.setText("Reallizar Prestamo");
        miPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPrestamoActionPerformed(evt);
            }
        });
        mnUsuario.add(miPrestamo);

        jMenuBar1.add(mnUsuario);

        mnLibros.setText("Libros");

        miLibrosPrestados.setText("Libros Prestados");
        miLibrosPrestados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLibrosPrestadosActionPerformed(evt);
            }
        });
        mnLibros.add(miLibrosPrestados);

        jMenuBar1.add(mnLibros);

        mnSalir.setText("Salir");

        miSalir.setText("Salir Aplicación");
        miSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalirActionPerformed(evt);
            }
        });
        mnSalir.add(miSalir);

        jMenuBar1.add(mnSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miUserNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUserNuevoActionPerformed
        quitarPaneles();
        /*En el jPanel de AltaUsuario le pasamos el objeto de tipo Empresa,
        llamado miEmpresa para que nos guarde el usuario.
        Si no lo ponemos nos saldrá el error javaNull...*/
        pAlta = new pnAltaUsuarios(miEmpresa);
        getContentPane().add(pAlta);
        pack();
    }//GEN-LAST:event_miUserNuevoActionPerformed

    private void miSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirActionPerformed
        int x = JOptionPane.showConfirmDialog(this, //DEVUELVE UN VALOR ENTERO 
                "¿DESEA SALIR DEL SISTEMA?", // MENSAJE DE CABECERA ENCIMA DE LOS BOTONES
                "SALIR DEL SISTEMA", // BARRA DE TITULO DE LA VENTANA
                JOptionPane.YES_NO_OPTION);                                     // LOS BOTONES 0 PARA EL CIERRE Y 1 PARA EL NO
        if (x == JOptionPane.YES_OPTION) {                                        //TAMBIEN ES VALIDO ESTA LINEA PARA EL IF EN VEZ DE EL 0
            //if (x == 0) {
            dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_miSalirActionPerformed

    private void miPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPrestamoActionPerformed
        quitarPaneles();
        pPrestamos = new pnPrestamos(miEmpresa);
        getContentPane().add(pPrestamos);
        pack();
    }//GEN-LAST:event_miPrestamoActionPerformed

    private void miLibrosPrestadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLibrosPrestadosActionPerformed
        quitarPaneles();
        pConsultas = new pnConsultas(miEmpresa);
        getContentPane().add(pConsultas);
        pack();
    }//GEN-LAST:event_miLibrosPrestadosActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int x = JOptionPane.showConfirmDialog(this, //DEVUELVE UN VALOR ENTERO 
                "¿DESEA SALIR DEL SISTEMA?", // MENSAJE DE CABECERA ENCIMA DE LOS BOTONES
                "SALIR DEL SISTEMA", // BARRA DE TITULO DE LA VENTANA
                JOptionPane.YES_NO_OPTION);                                     // LOS BOTONES 0 PARA EL CIERRE Y 1 PARA EL NO
        if (x == JOptionPane.YES_OPTION) {                                     //TAMBIEN ES VALIDO ESTA LINEA PARA EL IF EN VEZ DE EL 0
            //if (x == 0) {
            dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Biblioteca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miLibrosPrestados;
    private javax.swing.JMenuItem miPrestamo;
    private javax.swing.JMenuItem miSalir;
    private javax.swing.JMenuItem miUserNuevo;
    private javax.swing.JMenu mnLibros;
    private javax.swing.JMenu mnSalir;
    private javax.swing.JMenu mnUsuario;
    // End of variables declaration//GEN-END:variables
}
