/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import modelo.Empresa;
import modelo.Libros;
import modelo.Usuario;

/**
 *
 * @author 203pc19
 */
public class pnConsultas extends javax.swing.JPanel {

    Empresa miEmpresa;
    Usuario miUsuario;
    Libros miLibro;
    DefaultComboBoxModel modelo1;//comboBox de usuarios
    DefaultTableModel modelo2;//el jTable de los libros que tiene cada usuario

    /**
     * Creates new form pnConsultas
     */
    public pnConsultas(Empresa miEmpresa) {
        this.miEmpresa = miEmpresa;
        initComponents();
        modelo1 = new DefaultComboBoxModel();
        modelo2 = new DefaultTableModel();
        String[] titulos = {"ISBN", "TITULO", "AUTOR", "EDITORIAL"};// Son los titulos que va a tener cada columna. Total 2 columnas
        modelo2.setColumnIdentifiers(titulos);
        cmbUsuarios.setModel(modelo1);
        tblPrestamos.setModel(modelo2);
        cargarUsuarios();
        //cargarPrestamos();
    }

    private void cargarUsuarios() {
        ArrayList<Usuario> usuarios = miEmpresa.getUsuarios();
        for (int i = 0; i < usuarios.size(); i++) {
            if (usuarios.get(i).getlNuevos().size() > 0) {
                modelo1.addElement(usuarios.get(i));
            }
        }
    }

    /*private void cargarPrestamos() {
        miUsuario = (Usuario) cmbUsuarios.getSelectedItem();
        ArrayList<Libros> libro = miUsuario.getlNuevos();
        borrarFilas();
        for (int i = 0; i < libro.size(); i++) {
            Libros l = libro.get(i);// esto no me devuelve la posición del correo,
             //esto ya me devuelve el correo en concreto
            String[] datos = new String[modelo2.getColumnCount()];
            datos[0] = l.getIsbn();
            datos[1] = l.getTitulo();
            datos[2] = l.getAutor();
            datos[3] = l.getEditorial();
            modelo2.addRow(datos);
        }
    }*/
    public void borrarFilas() {
        int nFilas = modelo2.getRowCount();
        for (int i = 0; i < nFilas; i++) {
            modelo2.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        cmbUsuarios = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrestamos = new javax.swing.JTable();

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel5.setText("CONSULTA DE PRESTAMOS");

        cmbUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUsuariosActionPerformed(evt);
            }
        });

        jLabel1.setText("USUARIOS");

        tblPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPrestamos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cmbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUsuariosActionPerformed
        miUsuario = (Usuario) cmbUsuarios.getSelectedItem();
        ArrayList<Libros> libro = miUsuario.getlNuevos();
        borrarFilas();
        for (int i = 0; i < libro.size(); i++) {
            Libros l = libro.get(i);/* esto no me devuelve la posición del correo,
             esto ya me devuelve el correo en concreto*/
            String[] datos = new String[modelo2.getColumnCount()];
            datos[0] = l.getIsbn();
            datos[1] = l.getTitulo();
            datos[2] = l.getAutor();
            datos[3] = l.getEditorial();
            modelo2.addRow(datos);
        }
    }//GEN-LAST:event_cmbUsuariosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPrestamos;
    // End of variables declaration//GEN-END:variables
}
