/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.Conexion;
import controlador.GestorEnfermos;
import controlador.GestorMedicacion;
import controlador.GestorMedicacionEnfermo;
import controlador.GestorUsuarios;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Enfermo;
import modelo.Medicaciones;

/**
 *
 * @author Mario
 */
public class PnAltaMedicacion extends javax.swing.JPanel {

    Conexion bd;
    DefaultComboBoxModel modeloEnfermo;
    DefaultComboBoxModel modeloMedicacion;
    Enfermo miEnfermo;
    String numSegSocial;
    Medicaciones miMedicacion;
    String codMedicacion;

    /**
     * Creates new form PnAltaUsuario
     */
    public PnAltaMedicacion() {
        initComponents();
        bd = new Conexion();
        modeloEnfermo = new DefaultComboBoxModel();
        cmbEnfermo.setModel(modeloEnfermo);
        modeloMedicacion = new DefaultComboBoxModel();
        cmbMedicacion.setModel(modeloMedicacion);
        int resultado = bd.establecer("jdbc:mysql://localhost:3306/examen8615");// lo último es el nombre de la base de datos
        if (resultado != 0) {
            JOptionPane.showMessageDialog(this, "CONEXIÓN INCORRECTA");
            System.exit(0);
        }
        cargarMedicaciones();
        cargarEnfermos();
    }

    private void cargarMedicaciones() {
        GestorMedicacion m = new GestorMedicacion(bd);
        ArrayList<Medicaciones> medicaciones;
        medicaciones = m.consultaTodasMedicaciones();
        for (int i = 0; i < medicaciones.size(); i++) {
            modeloMedicacion.addElement(medicaciones.get(i));
        }
    }

    private void cargarEnfermos() {
        GestorEnfermos e = new GestorEnfermos(bd);
        ArrayList<Enfermo> enfermos;
        enfermos = e.consultaTodosEnfermos();
        for (int i = 0; i < enfermos.size(); i++) {
            modeloEnfermo.addElement(enfermos.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cmbEnfermo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbMedicacion = new javax.swing.JComboBox<>();

        jLabel1.setText("ALTA DE MEDICACION");

        jLabel5.setText("MEDICACION");

        btnAceptar.setText("ACEPTAR");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");

        cmbEnfermo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEnfermoActionPerformed(evt);
            }
        });

        jLabel6.setText("Enfermo");

        cmbMedicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMedicacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btnAceptar)
                        .addGap(85, 85, 85)
                        .addComponent(btnCancelar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel5)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cmbMedicacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbEnfermo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEnfermo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(cmbMedicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        GestorEnfermos gEnfermos = new GestorEnfermos(bd);
        GestorMedicacion gMedicacion = new GestorMedicacion(bd);
        GestorMedicacionEnfermo gMedicacionEnfermo = new GestorMedicacionEnfermo(bd);
        String segSocial, codMed;

        if (gMedicacionEnfermo.existeEnfermoMedicacion(numSegSocial, codMedicacion)) {
            JOptionPane.showMessageDialog(this, "EL PACIENTE YA TIENE ESA MEDICACION");
        } else {
            if (gMedicacionEnfermo.grabarMedicacionEnfermo(numSegSocial, codMedicacion) == 1) {
                /*le decimos si es igual a 1 porque solo añadimos un registro cada vez por lo
                que siempre nos devolvera 1 si la grabación es correcta*/
                JOptionPane.showMessageDialog(this, "REGISTRO AÑADIDO");
                /*modelo.removeAllElements();
                    cargarCursos();
                    generarId();*/
            } else {
                JOptionPane.showMessageDialog(this, "SE HA PRODUCIDO ALGÚN ERROR");
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void cmbEnfermoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEnfermoActionPerformed
        comboBoxEnfermos();
    }//GEN-LAST:event_cmbEnfermoActionPerformed

    private void cmbMedicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMedicacionActionPerformed
        comboBoxMedicacion();
    }//GEN-LAST:event_cmbMedicacionActionPerformed

    public void comboBoxMedicacion() {

        miMedicacion = (Medicaciones) modeloMedicacion.getSelectedItem();
        codMedicacion = miMedicacion.getCodMedicacion();

    }

    public void comboBoxEnfermos() {

        miEnfermo = (Enfermo) modeloEnfermo.getSelectedItem();
        numSegSocial = miEnfermo.getNumSegSocial();

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cmbEnfermo;
    private javax.swing.JComboBox<String> cmbMedicacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
