package Ventana;
//este jFrame "MiVentana" es el Main de los proyectos vistos hasta ahora

import Modelo.Curso;
import Modelo.Empresa;
import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author 203pc19
 */
public class MiVentana extends javax.swing.JFrame {

    Empresa miEmpresa;
    DefaultListModel modelo1, modelo2, modelo3, modelo4;

    /**
     * Creates new form Cursos
     */
    public MiVentana() {
        miEmpresa = new Empresa();
        /*Estos 4 modleos son colecciones. Es distinto que un array*/
        modelo1 = new DefaultListModel();//PARA LA LISTA DE NOMBRES CURSOS OFERTADOS
        modelo2 = new DefaultListModel();//PARA LA LISTA DE PRECIOS CURSOS OFERTADOS
        modelo3 = new DefaultListModel();//PARA LA LISTA DE NOMBRES CURSOS SELECCIONADOS
        modelo4 = new DefaultListModel();//PARA LA LISTA DE PRECIOS CURSOS SELECCIONADOS

        initComponents();
        lstCursosOfertados.setModel(modelo1);
        lstPreciosOfertados.setModel(modelo2);
        lstCursosSelec.setModel(modelo3);
        lstPreciosSelec.setModel(modelo4);
        cargarCursos();
        //La siguiente línea me agrega color a todo el jFrame
        this.getContentPane().setBackground(Color.MAGENTA);//hay que ponerlo despues de initComponents()
        Color color1 = new Color(1, 37, 245);// creamos un objeto de la clase color
        Color color2 = new Color(0, 0, 0);
        etSelecCursos.setForeground(color2.white);//para dar color a las etiquetas
    }

    private void cargarCursos() {
        Curso[] c = miEmpresa.getCursos();//GUARDAMOS EN "c" TODOS LOS DATOS DE CADA CURSO
        for (int i = 0; i < c.length; i++) {
            modelo1.addElement(c[i]);// ASI NOS MUESTRA EL NOMBRE GRACIAS @Override DE LA CLASE CURSO
            modelo2.addElement(c[i].getImporte());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgGrupo = new javax.swing.ButtonGroup();
        txtAlumno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCursosOfertados = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPreciosOfertados = new javax.swing.JList();
        btnAgregar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstCursosSelec = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstPreciosSelec = new javax.swing.JList();
        etSelecCursos = new javax.swing.JLabel();
        etTotalCursos = new javax.swing.JLabel();
        txtTotalCursos = new javax.swing.JTextField();
        etFormaPago = new javax.swing.JLabel();
        rbContado = new javax.swing.JRadioButton();
        rbCredito = new javax.swing.JRadioButton();
        btnCalcular = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        etIncremento = new javax.swing.JLabel();
        txtIncremento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ALUMNO");

        txtAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlumnoActionPerformed(evt);
            }
        });

        lstCursosOfertados.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCursosOfertadosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstCursosOfertados);

        jLabel2.setText("ALUMNO");

        lstPreciosOfertados.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPreciosOfertadosValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstPreciosOfertados);
        lstPreciosOfertados.getAccessibleContext().setAccessibleParent(jLabel2);

        btnAgregar.setText(">>");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnQuitar.setText("<<");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        jLabel1.setText("Cursos Seleccionados");

        jLabel3.setText("Precios Seleccionados");

        lstCursosSelec.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCursosSelecValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstCursosSelec);

        lstPreciosSelec.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPreciosSelecValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(lstPreciosSelec);

        etSelecCursos.setText("Seleccionar Cursos");

        etTotalCursos.setText("TOTAL CURSOS");

        txtTotalCursos.setEditable(false);

        etFormaPago.setText("Forma de Pago");

        bgGrupo.add(rbContado);
        rbContado.setSelected(true);
        rbContado.setText("Contado");

        bgGrupo.add(rbCredito);
        rbCredito.setText("Crédito");

        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        etIncremento.setText("Incremento");

        txtIncremento.setEditable(false);

        jLabel4.setText("Descuento");

        txtDescuento.setEditable(false);

        jLabel5.setText("Total");

        txtTotal.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCalcular)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etFormaPago)
                        .addGap(28, 28, 28)
                        .addComponent(rbContado)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnLimpiar)
                        .addGap(54, 54, 54)
                        .addComponent(btnSalir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rbCredito))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(etIncremento)
                        .addGap(18, 18, 18)
                        .addComponent(txtIncremento, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(etSelecCursos))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregar)
                            .addComponent(btnQuitar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etTotalCursos)
                                .addGap(39, 39, 39)
                                .addComponent(txtTotalCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAgregar)
                                .addGap(26, 26, 26)
                                .addComponent(btnQuitar)
                                .addGap(40, 40, 40))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etSelecCursos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(etTotalCursos)
                        .addComponent(txtTotalCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(etFormaPago)
                        .addComponent(rbContado)
                        .addComponent(rbCredito)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(btnLimpiar)
                    .addComponent(btnSalir))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etIncremento)
                    .addComponent(txtIncremento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlumnoActionPerformed

    private void lstCursosOfertadosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCursosOfertadosValueChanged
        int indice;
        indice = lstCursosOfertados.getSelectedIndex();
        lstPreciosOfertados.setSelectedIndex(indice);
    }//GEN-LAST:event_lstCursosOfertadosValueChanged

    private void lstPreciosOfertadosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPreciosOfertadosValueChanged
        /*Con este método hacemos que cuando damos en un precio me coga el curso tambien*/
        int indice;
        indice = lstPreciosOfertados.getSelectedIndex();//Con estas dos lineas hacemos la seleccion a la vez
        lstCursosOfertados.setSelectedIndex(indice);
    }//GEN-LAST:event_lstPreciosOfertadosValueChanged

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Curso c;//con el objeto "c" llamamos a la denomincacion de la clase Curso
        float importe;
        int indice = lstCursosOfertados.getSelectedIndex();
        if (indice == -1) {
            JOptionPane.showMessageDialog(this, "Primero selecciona el curso");
        } else {
            /*Ponemos "Curso" entre los parentesis porque en el metodo
             cargarCursos() hemos puesto "modelo1.addElement(c[i]);"
             Si ponemos puesto modelo1.addElement(c[i]).getDenominacion();
             en el método cargarCursos() tendriamos que poner:
             String c;
             c= (String)..., dependiendo del tipo de datos que sea*/
            c = (Curso) lstCursosOfertados.getSelectedValue();
            importe = (Float) lstPreciosOfertados.getSelectedValue();
            modelo3.addElement(c);//el "addElement" te lo agrega al final del siguiente elmento
            modelo4.addElement(importe);
            modelo1.remove(indice);
            /*modelo2 le decimos que está también en indice porque cuando seleccionamos
             el modelos1 (que es la denominacion), también seleccionamos automaticamente
             el modelo2 (que es el importe)*/
            modelo2.remove(indice);
            calculoImporte();
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        Curso c;//con el objeto "c" llamamos a la denomincacion de la clase Curso
        float importe;
        int indice = lstCursosSelec.getSelectedIndex();
        if (indice == -1) {
            JOptionPane.showMessageDialog(this, "Primero selecciona el curso");
        } else {
            c = (Curso) lstCursosSelec.getSelectedValue();
            importe = (Float) lstPreciosSelec.getSelectedValue();
            modelo3.remove(indice);//el "remove"te lo borra
            modelo4.remove(indice);
            modelo1.addElement(c);
            /*modelo2 le decimos que está también en indice porque cuando seleccionamos
             el modelos1 (que es la denominacion), también seleccionamos automaticamente
             el modelo2 (que es el importe)*/
            modelo2.addElement(importe);
            calculoImporte();
        }
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void lstCursosSelecValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCursosSelecValueChanged
        int indice;
        indice = lstCursosSelec.getSelectedIndex();
        lstPreciosSelec.setSelectedIndex(indice);
    }//GEN-LAST:event_lstCursosSelecValueChanged

    private void lstPreciosSelecValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPreciosSelecValueChanged
        int indice;
        indice = lstPreciosSelec.getSelectedIndex();
        lstCursosSelec.setSelectedIndex(indice);
    }//GEN-LAST:event_lstPreciosSelecValueChanged

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtAlumno.setText("");
        modelo1.clear();
        modelo2.clear();
        modelo3.clear();
        modelo4.clear();
        cargarCursos();
        rbContado.setSelected(true);
        txtTotalCursos.setText("");
        txtIncremento.setText("");
        txtDescuento.setText("");
        txtTotal.setText("");
        btnCalcular.setEnabled(false);
        btnLimpiar.setEnabled(false);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        float descuento, incremento, totalCursos, totalPagar;
        try {
            totalCursos = Float.parseFloat(txtTotalCursos.getText());
            if (rbContado.isSelected()) {
                incremento = 0;
                descuento = 0.5f * totalCursos;
            } else {
                incremento = 0.1f * totalCursos;
                descuento = 0;
            }
            totalPagar = totalCursos + incremento - descuento;
            //ESTAS TRES SIGUIENTES LÍNEAS SIRVEN PARA CONVERTIR LOS VALORES A STRING
            //para que no de error
            txtTotal.setText(String.valueOf(totalPagar));
            txtDescuento.setText(String.valueOf(descuento));
            txtIncremento.setText(String.valueOf(incremento));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "HAY QUE SELECCIONAR UN CURSO");
        }
    }//GEN-LAST:event_btnCalcularActionPerformed
    private void calculoImporte() {
        float total = 0;
        for (int i = 0; i < modelo4.size(); i++) {//EL "SIZE" ES IGUAL QUE EL "LENGTH"
            /*Poniendo el float entre parentesis delanta, convertimos el valor del modelo4
             a tipo float. Se llama castear*/
            total = total + (float) modelo4.get(i);
        }
        txtTotalCursos.setText(String.valueOf(total));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgGrupo;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel etFormaPago;
    private javax.swing.JLabel etIncremento;
    private javax.swing.JLabel etSelecCursos;
    private javax.swing.JLabel etTotalCursos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList lstCursosOfertados;
    private javax.swing.JList lstCursosSelec;
    private javax.swing.JList lstPreciosOfertados;
    private javax.swing.JList lstPreciosSelec;
    private javax.swing.JRadioButton rbContado;
    private javax.swing.JRadioButton rbCredito;
    private javax.swing.JTextField txtAlumno;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtIncremento;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalCursos;
    // End of variables declaration//GEN-END:variables
}
