/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modelo.Empresa;
import modelo.Linea;
import modelo.Paradas;

/**
 *
 * @author 203pc19
 */
public class PnAltaLineas extends javax.swing.JPanel {

    Empresa miEmpresa;
    DefaultListModel modeloPrimera;
    DefaultListModel modeloUltima;

    /**
     * Creates new form PnAltaLineas
     */
    public PnAltaLineas(Empresa miEmpresa) {
        initComponents();
        this.miEmpresa = miEmpresa;
        modeloPrimera = new DefaultListModel();
        lstPrimera.setModel(modeloPrimera);
        modeloUltima = new DefaultListModel();
        lstUltima.setModel(modeloUltima);
        cargarPrimeraParada();
        cargarUltimaParada();
    }

    private void cargarPrimeraParada() {
        ArrayList<Paradas> miParada = miEmpresa.getParadas();
        for (int i = 0; i < miParada.size(); i++) {
            modeloPrimera.addElement(miParada.get(i));
        }
    }

    private void cargarUltimaParada() {
        ArrayList<Paradas> miParada = miEmpresa.getParadas();
        for (int i = 0; i < miParada.size(); i++) {
            int posPrimera = lstUltima.getSelectedIndex();
            if (i != posPrimera) {
                modeloUltima.addElement(miParada.get(i));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDenominacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFrecuencia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPrimera = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstUltima = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        txtIntermedias = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        jLabel1.setText("ALTA DE LÍNEAS");

        jLabel2.setText("CÓDIGO");

        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoKeyPressed(evt);
            }
        });

        jLabel3.setText("DENOMINACIÓN");

        txtDenominacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDenominacionKeyPressed(evt);
            }
        });

        jLabel4.setText("FRECUENCIA");

        txtFrecuencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFrecuenciaKeyPressed(evt);
            }
        });

        jLabel5.setText("1ª PARADA");

        lstPrimera.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstPrimera.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lstPrimeraKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(lstPrimera);

        jLabel6.setText("ÚLTIMA PARADA");

        lstUltima.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstUltima.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lstUltimaKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(lstUltima);

        jLabel7.setText("PARADAS INTERMEDIAS");

        txtIntermedias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIntermediasKeyPressed(evt);
            }
        });

        btnAceptar.setText("ACEPTAR");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(159, 159, 159))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(28, 28, 28)
                        .addComponent(txtIntermedias, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(28, 28, 28)
                        .addComponent(txtDenominacion, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btnAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtDenominacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txtFrecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(txtIntermedias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String codigo, denominacion, primeraParada, ultimaParada;
        String frecuencia, paradasIntermedias;
        Linea miLinea;
        Paradas p1;
        Paradas p2;

        codigo = txtCodigo.getText().trim();
        denominacion = txtDenominacion.getText();
        frecuencia = txtFrecuencia.getText();
        paradasIntermedias = txtIntermedias.getText();

        int posPrimera = lstPrimera.getSelectedIndex();
        int posUltima = lstUltima.getSelectedIndex();
        if (!miEmpresa.buscarLinea(codigo)) {
            if (codigo.length() > 0 && denominacion.length() > 0
                    && frecuencia.length() > 0 && paradasIntermedias.length() > 0
                    && posPrimera > -1 && posUltima > -1) {
                /*el "-1" es para el jlist. Si no hay nada de selecionado, devuelve "-1"*/
                if (posPrimera != posUltima) {
                    p1 = miEmpresa.getUnaParada(posPrimera);
                    p2 = miEmpresa.getUnaParada(posUltima);

                    miLinea = new Linea(codigo, denominacion, frecuencia, p1.getDenominacion(), p2.getDenominacion(), paradasIntermedias);
                    miEmpresa.getLineas().add(miLinea);
                    miLinea.getParadas().add(p1);
                    miLinea.getParadas().add(p2);

                    limpiar();
                    JOptionPane.showMessageDialog(this, "LÍNEA AÑADIDA");
                } else {
                    JOptionPane.showMessageDialog(this, "ESA PARADA YA ESTÁ COGIDA");
                }
            } else {
                JOptionPane.showMessageDialog(this, "HAY CAMPOS VACIOS");
            }
        } else {
            JOptionPane.showMessageDialog(this, "YA EXISTE UNA LÍNEA CON ESE CÓDIGO");
            limpiar();
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyPressed
        switch (evt.getKeyCode()) {
            case 10:
                txtDenominacion.requestFocus();
                break;
            case 27:
                txtCodigo.setText("");
        }
    }//GEN-LAST:event_txtCodigoKeyPressed

    private void txtDenominacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDenominacionKeyPressed
        switch (evt.getKeyCode()) {
            case 10:
                txtFrecuencia.requestFocus();
                break;
            case 27:
                txtDenominacion.setText("");
        }
    }//GEN-LAST:event_txtDenominacionKeyPressed

    private void txtFrecuenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFrecuenciaKeyPressed
        switch (evt.getKeyCode()) {
            case 10:
                lstPrimera.requestFocus();
                break;
            case 27:
                txtFrecuencia.setText("");
        }
    }//GEN-LAST:event_txtFrecuenciaKeyPressed

    private void txtIntermediasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIntermediasKeyPressed
        switch (evt.getKeyCode()) {
            case 10:
                btnAceptar.doClick();
                break;
            case 27:
                txtIntermedias.setText("");
        }
    }//GEN-LAST:event_txtIntermediasKeyPressed

    private void lstPrimeraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstPrimeraKeyPressed
        switch (evt.getKeyCode()) {
            case 10:
                lstUltima.requestFocus();
                break;
        }
    }//GEN-LAST:event_lstPrimeraKeyPressed

    private void lstUltimaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstUltimaKeyPressed
        switch (evt.getKeyCode()) {
            case 10:
                txtIntermedias.requestFocus();
                break;
        }
    }//GEN-LAST:event_lstUltimaKeyPressed

    public void limpiar() {
        txtCodigo.setText("");
        txtDenominacion.setText("");
        txtFrecuencia.setText("");
        txtIntermedias.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lstPrimera;
    private javax.swing.JList lstUltima;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDenominacion;
    private javax.swing.JTextField txtFrecuencia;
    private javax.swing.JTextField txtIntermedias;
    // End of variables declaration//GEN-END:variables
}
