/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Empresa;
import modelo.Linea;
import modelo.Paradas;
import modelo.miModelo;

/**
 *
 * @author 203pc19
 */
public class PnConsulta extends javax.swing.JPanel {

    Empresa miEmpresa;
    Linea miLinea;
    miModelo modeloTabla;
    DefaultComboBoxModel modeloLinea;

    /**
     * Creates new form PnConsulta
     */
    public PnConsulta(Empresa miEmpresa) {
        initComponents();
        this.miEmpresa = miEmpresa;
        modeloLinea = new DefaultComboBoxModel();
        cmbLinea.setModel(modeloLinea);

        String[] titulos = {"CÓDIGO", "DENOMINACIÓN"};// Son los titulos que va a tener cada columna.
        modeloTabla = new miModelo();
        modeloTabla.setColumnIdentifiers(titulos);
        tblParadas.setModel(modeloTabla);
        cargarLineas();
    }

    private void cargarLineas() {
        ArrayList<Linea> linea = miEmpresa.getLineas();
        for (int i = 0; i < linea.size(); i++) {
            modeloLinea.addElement(linea.get(i));

        }
    }

    public void borrarFilas() {
        int nFilas = modeloTabla.getRowCount();
        for (int i = 0; i < nFilas; i++) {
            modeloTabla.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbLinea = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblParadas = new javax.swing.JTable();
        btnBorrar = new javax.swing.JButton();

        jLabel1.setText("CONSULTA DE LÍNEAS");

        cmbLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLineaActionPerformed(evt);
            }
        });
        cmbLinea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbLineaKeyPressed(evt);
            }
        });

        jLabel2.setText("DENOMINACIÓN");

        tblParadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblParadas);

        btnBorrar.setText("BORRAR");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2)
                        .addGap(42, 42, 42)
                        .addComponent(cmbLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBorrar)
                .addGap(174, 174, 174))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBorrar)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLineaActionPerformed
        /*  miLinea = (Linea) cmbLinea.getSelectedItem();
         ArrayList<Paradas> parada = miLinea.getParadas();
         borrarFilas();
         for (int i = 0; i < parada.size(); i++) {
         Paradas p = parada.get(i);/* esto no me devuelve la posición del correo,
         esto ya me devuelve el correo en concreto*/

        /* String[] datos = new String[modeloTabla.getColumnCount()];
         datos[0] = p.getCodigo();
         datos[1] = p.getDenominacion();
         modeloTabla.addRow(datos);
         }*/
        seleccionarLineas();
    }//GEN-LAST:event_cmbLineaActionPerformed

    private void seleccionarLineas() {

        miLinea = (Linea) cmbLinea.getSelectedItem();
        ArrayList<Paradas> parada = miLinea.getParadas();
        borrarFilas();
        for (int i = 0; i < parada.size(); i++) {
            Paradas p = parada.get(i);/* esto no me devuelve la posición del correo,
             esto ya me devuelve el correo en concreto*/

            String[] datos = new String[modeloTabla.getColumnCount()];
            datos[0] = p.getCodigo();
            datos[1] = p.getDenominacion();
            modeloTabla.addRow(datos);

        }
    }

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        miLinea = (Linea) modeloLinea.getSelectedItem();

        int x = JOptionPane.showConfirmDialog(this, "¿DESEA ELIMINAR LA LÍNEA?", "BORRAR LÍNEAS",
                JOptionPane.YES_NO_OPTION);

        if (x == JOptionPane.YES_OPTION) {
            int pos = cmbLinea.getSelectedIndex();
            modeloLinea.removeElementAt(pos);
            miEmpresa.getLineas().remove(pos);
            borrarFilas();
            JOptionPane.showMessageDialog(this, "LÍNEA BORRADA");

            miLinea = (Linea) cmbLinea.getSelectedItem();
            ArrayList<Paradas> parada = miLinea.getParadas();
            borrarFilas();
            if (modeloLinea.getSize() > 0) {
                seleccionarLineas();
            }
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void cmbLineaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbLineaKeyPressed
        switch (evt.getKeyCode()) {
            case 112:
                JOptionPane.showMessageDialog(this, "La línea que desea ver");
        }

    }//GEN-LAST:event_cmbLineaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JComboBox cmbLinea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblParadas;
    // End of variables declaration//GEN-END:variables
}
